version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: studioswarm
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbscripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  backend:
    image: mayurchoubey/studioswarm-backend:latest  # Using prebuilt image from Docker Hub
    container_name: studioswarm_server
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgrespassword@postgres:5432/studioswarm"
    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    image: mayurchoubey/studioswarm-frontend:latest  # Using prebuilt image from Docker Hub
    container_name: studioswarm_frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_PATH: /api/studioswarm
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: studioswarm_nginx
    ports:
      - "4000:4000"  # Expose frontend
      - "8001:8001"  # Backend API
      - "9000-9100:9000-9100"  # Additional ports for future scaling
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
